# Generated by Django 5.0.14 on 2025-11-15 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("APARTMENT", "Apartment"),
                            ("HOUSE", "House"),
                            ("VILLA", "Villa"),
                            ("STUDIO", "Studio"),
                            ("TOWNHOUSE", "Townhouse"),
                            ("PENTHOUSE", "Penthouse"),
                            ("COMMERCIAL", "Commercial"),
                            ("LAND", "Land"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Internal title for your reference", max_length=255
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="USA", max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Property price", max_digits=12
                    ),
                ),
                ("bedrooms", models.IntegerField(blank=True, null=True)),
                (
                    "bathrooms",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "square_feet",
                    models.IntegerField(
                        blank=True, help_text="Total square footage", null=True
                    ),
                ),
                (
                    "lot_size",
                    models.IntegerField(
                        blank=True, help_text="Lot size in square feet", null=True
                    ),
                ),
                ("year_built", models.IntegerField(blank=True, null=True)),
                (
                    "key_features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of key features (e.g., pool, garage, fireplace)",
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("PROFESSIONAL", "Professional"),
                            ("LUXURY", "Luxury"),
                            ("FRIENDLY", "Friendly"),
                            ("CONCISE", "Concise"),
                            ("DETAILED", "Detailed"),
                        ],
                        default="PROFESSIONAL",
                        max_length=20,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("FAMILIES", "Families"),
                            ("YOUNG_PROFESSIONALS", "Young Professionals"),
                            ("RETIREES", "Retirees"),
                            ("INVESTORS", "Investors"),
                            ("LUXURY_BUYERS", "Luxury Buyers"),
                            ("FIRST_TIME_BUYERS", "First-time Buyers"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=30,
                    ),
                ),
                (
                    "additional_notes",
                    models.TextField(
                        blank=True,
                        help_text="Any additional information to include in the description",
                    ),
                ),
                (
                    "generated_description",
                    models.TextField(
                        blank=True, help_text="AI-generated property description"
                    ),
                ),
                (
                    "edited_description",
                    models.TextField(
                        blank=True, help_text="User-edited version of the description"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "generation_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times description was regenerated",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing",
                "verbose_name_plural": "Listings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="listings_li_user_id_a04e5d_idx",
                    ),
                    models.Index(
                        fields=["user", "is_favorite"],
                        name="listings_li_user_id_6058d2_idx",
                    ),
                ],
            },
        ),
    ]
